spring:
  application:
    name: medflow
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 'gdfgwe123'
    url: jdbc:postgresql://localhost:5432/postgres
